%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt
%
% Auto-generated by MATLAB on 11-Aug-2022 23:22:21

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = [64, 64];
opts.Delimiter = ["\t", "_"];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "VarName5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"];
opts.SelectedVariableNames = "VarName5";
opts.VariableTypes = ["string", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"], "EmptyFieldRule", "auto");

% Import the data
testeana = readtable("C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt", opts);

%% Convert to output type
testeana = table2cell(testeana);
numIdx = cellfun(@(x) ~isnan(str2double(x)), testeana);
testeana(numIdx) = cellfun(@(x) {str2double(x)}, testeana(numIdx));

%% Clear temporary variables
clear opts