%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt
%
% Auto-generated by MATLAB on 11-Aug-2022 23:08:36



%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ["\t", "_"];

% Specify column names and types
opts.VariableNames = ["SMP", "VarName2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"];
opts.SelectedVariableNames = ["SMP", "VarName2"];
opts.VariableTypes = ["categorical", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SMP", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt", opts);

%% Convert to output type
SMP = tbl.SMP;
VarName2 = tbl.VarName2;

%% Clear temporary variables
clear opts tbl