%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt
%
% Auto-generated by MATLAB on 11-Aug-2022 23:24:44

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ["\t", "_"];

% Specify column names and types
opts.VariableNames = ["SMP", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "START", "RECORDING", "VarName29"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName29", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SMP", "RECORDING", "VarName29"], "EmptyFieldRule", "auto");

% Import the data
testeana3 = readtable("C:\Users\anapa\Documents\ppgeb_masters\teste_ana.txt", opts);


%% Clear temporary variables
clear opts